@startuml
'https://plantuml.com/class-diagram
interface PayStrategy{
    void askForDetailInfo()
    void getDetailInfo(List<String> info)
    void pay()
}

PayStrategy <|.. WechatPay
PayStrategy <|.. AliPay
PayStrategy <|.. CreditCard

class Order{
    PayStrategy p
    void processOrder(PayStrategy p)
}

PayStrategy o-- Order

Order <.. Client
@enduml