@startuml
'https://plantuml.com/class-diagram
note as N
    <b> 观察者模式 </b>
    <i> 非常类似于推送式消息队列 </i>
    <i> 一个发送端 </i>
    <i> 多个订阅端 </i>
end note
interface Observer{
    fetch(Float tempature)
}

interface subject{
    register(Observer o)
    remove(Observer o)
    notifyAll()
}
class WeatherData{
    ArrayList<Observer>

}
subject <|.. WeatherData
Observer <.. WeatherData
Observer <|.. Baidu
Observer <|..Sina

WeatherData <.. Client
Baidu <.. Client
Sina <.. Client

@enduml