@startuml
'https://plantuml.com/class-diagram
interface Approve{
    Approver setNextApprover(Approver approver);
    void processRequest(SchoolRequest schoolRequest);
    void submitToNextApprover(SchoolRequest schoolRequest);
}

SchoolRequest <.. Approve
Approve <|.. AbstractApprove
abstract class AbstractApprove{
}
Approve o-- Approve
AbstractApprove <|--DepartmentApprove
AbstractApprove <|--CollegeApprove
AbstractApprove <|--SchoolMasterApprove

SchoolRequest <.. Client
DepartmentApprove <.. Client
CollegeApprove <.. Client
SchoolMasterApprove <.. Client
@enduml