@startuml
'https://plantuml.com/class-diagram
note as N
    <b> 聚合 aggregation</b>
    <i> 不是天生就在一起的比如人和信用卡</i>
end note
class Mouse
class Monitor
class Computer{
    Mouse mouse
    Monitor monitor
    void setMouse(Mouse m)
    void setMonitor(Monitor m)
}

Mouse *-- Computer
Monitor *-- Computer
@enduml